name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # Cambia in "master" se il tuo ramo principale si chiama così
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inserisci variabili Firebase
        run: |
          sed -i 's/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g' index.html
          sed -i 's/FIREBASE_AUTH_DOMAIN/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' index.html
          sed -i 's/FIREBASE_AUTH_PROJECTID/${{ secrets.FIREBASE_AUTH_PROJECTID }}/g' index.html
          sed -i 's/FIREBASE_AUTH_STORAGEBUCKET/${{ secrets.FIREBASE_AUTH_STORAGEBUCKET }}/g' index.html
          sed -i 's/FIREBASE_AUTH_MESSAGINGSENDERID/${{ secrets.FIREBASE_AUTH_MESSAGINGSENDERID }}/g' index.html
          sed -i 's/FIREBASE_API_APPID/${{ secrets.FIREBASE_API_APPID }}/g' index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
